apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
type: Opaque
stringData:
  type: git
  url: https://github.com/KurosakiIchigo900/argocd-app-config-main.git
  username: S3Vyb3Nha2lJY2hpZ285MDA=
  password: QXJhdmluZEA5MDA=