apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynewapp
spec:
  selector:
    matchLabels:
      app: mynewapp
  replicas: 2
  template:
    metadata:
      labels:
        app: mynewapp
    spec:
      containers:
      - name: mynewapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
        
